version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:admin@localhost:27017/admin --quiet
      interval: 10s
      retries: 5
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 20s

  ms-event-manager:
    build: ./ms-event-manager
    container_name: ms-event-manager
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongodb:27017/db_event?authSource=admin
      - TICKET=http://ms-ticket-manager:8081
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  ms-ticket-manager:
    build: ./ms-ticket-manager
    container_name: ms-ticket-manager
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongodb:27017/db_ticket?authSource=admin
      - EVENT=http://ms-event-manager:8080
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
    ports:
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  mongodb_data:
  rabbitmq_data:
