spring:
  application:
    name: ms-event-manager
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      #uri: mongodb://localhost:27017/db_ticket


management:
  endpoints:
    web:
      exposure:
        include: health, info

msticket:
  tickets:
    ticket: ${TICKET}